### PR TITLE
feat: Add GitLab CLI authentication option

### PR DESCRIPTION
**Pull request by gr4cza**
This pull request introduces support for GitLab CLI authentication.

### CODE REVIEW

**Comment by gr4cza** [comment]
@abhinav, I was only able to finish the basic implementation. It still requires some cleanup and testing, but I’ll only be able to work on it tomorrow. Feel free to tinker with it if you’d like!

**Comment by abhinav** [comment]
Ack. I'll try to poke at this later today.

**Comment by abhinav** [comment]
@gr4cza I tweaked a bunch. Will merge when CI passes. LMK if you see any issues with my changes.

**Comment by gr4cza** [comment]
@abhinav Thank you!
>I like to avoid having multiple places invoke the same CLI separately
with similar-ish handling of output/etc. In such a case, it's useful
to put the os/exec's behind an abstraction of some kind.
I felt there might be a better way to do this, but as I mentioned, I’m completely new to Go. It requires a different way of thinking compared to Java/Kotlin.

What are your plans to release it? I'm really exited to install it from brew 🤩

**Comment by abhinav** [comment]
It's out in v0.9.0!
You should be able to `brew install` it once https://github.com/Homebrew/homebrew-core/pull/199068 is merged.

**Comment by gr4cza** [comment]
@abhinav thank you for all the support! 🎉

**Pull request merged**
