### PR TITLE
doc: Update for GitLab support

### PR DESCRIPTION
**Pull request by abhinav**
Update documentation website to reflect the new GitLab support
from #477.

refs #485

### CODE REVIEW

**Comment by abhinav** [comment]
This change is part of the following stack:

- #487 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Comment by abhinav** [comment]
@gr4cza Took a pass over the docs to add GitLab. 
Do you know the answer to these questions?

- Is GitLab also subject to the "squash-merges require restacking" limitation
- What are the steps for GitLab Enterprise (is that what it's called?)

(I'm happy to update the docs if I have the answers, but you can also PR against this branch if you want to add more than that.)

**Comment by gr4cza** [comment]
@abhinav I just did the testing for `squash-merges require restacking` and saw that you already verified it. Anyway, I came to the same conclusion. 

For the _Enterprise_ part:
I guess the service which is interesting to us called GitLab Self-hosted. That is, when the Base URL (and the API url) differs from the main gitlab.com. There will be a problem with the OAuth authentication. In a Self-hosted GitLab there will not be any `git-spice` OAuth client set up. So first the server admin has to create a new Application. But the problem is that this application will have a different clientId from what is hardcoded to git-spice currently. So we have to make it configurable.

@abhinav I just finished testing `squash-merges require restacking` and noticed that you’ve already verified it. Anyway, I came to the same conclusion.

For the _Enterprise_ part:
I believe the service we’re interested in is called GitLab Self-hosted. That is, when the Base URL (and the API URL) differs from the main gitlab.com. In such cases, there will be an issue with OAuth authentication. In a Self-hosted GitLab instance, there won’t be any preconfigured `git-spice` OAuth client. Therefore, the server admin will first need to create a new Application. However, this application will have a different `clientId` than the one currently hardcoded into git-spice.  Because of that, I think we’ll need to make it configurable.

**Comment by gr4cza** [comment]
@abhinav I just finished testing `squash-merges require restacking` and noticed that you’ve already verified it. Anyway, I came to the same conclusion.

For the _Enterprise_ part:
I believe the service we’re interested in is called GitLab Self-hosted. That is, when the Base URL (and the API URL) differs from the main gitlab.com. In such cases, there will be an issue with OAuth authentication. In a Self-hosted GitLab instance, there won’t be any preconfigured `git-spice` OAuth client. Therefore, the server admin will first need to create a new Application. However, this application will have a different `clientId` than the one currently hardcoded into git-spice.  Because of that, I think we’ll need to make it configurable.

**Comment by abhinav** [comment]
> Therefore, the server admin will first need to create a new Application. However, this application will have a different clientId than the one currently hardcoded into git-spice. Because of that, I think we’ll need to make it configurable.

Ack. We can do that. It'll just be another hidden flag like this with a config key like `forge.gitlab.oauth.clientID`. 

https://github.com/abhinav/git-spice/blob/ccf453784da40f13c0ffc5174ebc960261f60a4a/internal/forge/gitlab/forge.go#L29

gitlab.Forge would get a helper `OAuthClientID()` method that returns the configured value from options or the hard-coded one, and the DeviceFlowAuthenticator would be called with that.

If you have the time to open a PR for that, that would be cool.
Otherwise, I'll have time later tonight/tomorrow. 

After that I'll update this PR with relevant documentation for GitLab Self-Hosted, and we should be good to go.

**Comment by gr4cza** [comment]
I will try to do it tonight! Btw I did some research about how can we add gitlab-cli auth support as well and I think I find a way, so I will try to add that too.

**Comment by abhinav** [comment]
@gr4cza I'm going to merge the doc updates. It covers Self-Hosted, OAuth in self-hosted, and other things we discuss. I think I got everything. Anything else, I'm happy to iterate on in the future.

**Comment by abhinav** [comment]
image

went wild with pressing the wrong buttons there 😅

**Pull request merged**
